CREATE TABLE ESTUDIANTES (
	RUT VARCHAR (12) PRIMARY KEY,
	NOMBRE VARCHAR (50),
	CURSO VARCHAR (50),
	NIVEL SMALLINT
);

SELECT * FROM ESTUDIANTES;

INSERT INTO ESTUDIANTES (RUT, NOMBRE, CURSO, NIVEL) VALUES ('20934095-9','Julian Perez', 'Instrumentos de Cuerda', 3);